name: Deploy to SIGPAD Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Version
        id: version
        run: echo ::set-output name=VERSION::$(git describe --abbrev=0 --tags)

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Upload Files
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --rsync-path="sudo rsync"
          path: dist/*
          remote_path: /var/www/landing
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
